name: wqmcs

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: wqmcs-app
    container_name: wqmcs-app
    restart: unless-stopped
    networks:
      - wqmcs-network

  db:
    image: mysql:8.0
    container_name: wqmcs-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - wqmcs-database:/var/lib/mysql
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - wqmcs-network

  web-server:
    image: nginx:stable-alpine-slim
    container_name: wqmcs-web-server
    restart: unless-stopped 
    volumes:
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - wqmcs-network
    depends_on:
      - app

networks:
  wqmcs-network:
    driver: bridge

volumes:
  wqmcs-database: