name: wqmcs

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: wqmcs-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
     - ./:/var/www
    networks:
      - wqmcs-network

  db:
    image: mysql:8.0
    container_name: wqmcs-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - wqmcs-network
    depends_on:
      - app

  webserver:
    image: nginx:1.17-alpine
    container_name: wqmcs-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - wqmcs-network
    depends_on:
      - app


networks:
  wqmcs-network:
    driver: bridge