services:
  app:
    image: wqmcs:dev
    container_name: wqmcs-app-dev
    volumes:
      - ./:/var/www

  web-server:
    ports:
      - 8080:80
    volumes:
      - ./docker-compose/nginx:/etc/nginx/conf.d/
      - ./:/var/www
    